
# All ESGF Node Componenets

- hosts: spock
  # strategy: free
  become: yes
  # connection: paramiko
  any_errors_fatal: true
  vars:
    hostkey_src: /tmp/hostkey.pem
    hostcert_src: /tmp/hostcert.pem
    cachain_src: /tmp/hostcert.pem
  vars_files:
    - secrets.yml
  tasks:
    # Copy keys and certs
    - name: Copy hostkey
      copy: src=../../insecure_private_key dest={{ hostkey_src }}

    - name: Copy hostcert
      copy: src=../../server.pem dest={{ hostcert_src }}

    # Get the admin password
    - name: Include the admin passwd role
      block:
        - include_role:
            name: passwd
      tags: always
  
    - name: Verify variables
      block:
        - include_role:
            name: verify
      tags: always

    - name: Base
      block:
        - include_role:
            name: base
      tags:
        - always
        - base

    - name: IDP
      block:
        - include_role:
            name: idp
      tags: idp
      when: "'idp' in group_names"

    - name: Index
      block:
        - include_role:
            name: index
      tags: index
      when: "'index' in group_names"

    - name: Data
      block:
        - include_role:
            name: data
      tags: data
      when: "'data' in group_names"

    - name: Publisher
      block:
        - include_role:
            name: publisher
      tags:
        - data
        - publisher
      when: "'data' in group_names"
